Fizzbuzz/Models/FizzbuzzModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Fizzbuzz.Models;

namespace Fizzbuzz.Models
{
    public class FizzbuzzModel
    {
        public int PageSize = 20;
        public int CurrentPage = 1;
        public int TotalPages = 1;

        [Range(1, 1000, ErrorMessage = "Value must be a whole number between 1 and 1000")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:#}")]
        public int Count { get; set; }
        
        public List<FizzbuzzResultItem> Results { get; set; }

        public void GenerateResults()
        {
            CurrentPage = 1;
            TotalPages = 0;
            bool IsWednesday = DateTime.Now.DayOfWeek == DayOfWeek.Wednesday ? true : false;
            if (Count > 0 && Count < 1001)
            {
                Results = new List<FizzbuzzResultItem>();
                for (int i = 1; i <= Count; i++)
                {
                    FizzbuzzResultItem newItem = new FizzbuzzResultItem();
                    newItem.Value = i;
                    /*
                     Where the number is divisible by 3, you should instead print ‘fizz’
                     Where the number is divisible by 5, you should instead print 'buzz'
                     Where the number is divisible by 3 AND 5, you should instead print ‘fizz buzz’
                     Change the logic so that if today is Wednesday, the words 'wizz' and ‘wuzz' are substituted for 'fizz' and 'buzz'
                    */

                    if (newItem.Value % 3 == 0)
                    {
                        newItem.IsDivisibleByThree = true;
                        newItem.IsDivisibleByThreeText = IsWednesday ? "wizz" : "fizz";
                    }

                    if (newItem.Value % 5 == 0)
                    {
                        newItem.IsDivisibleByFive = true;
                        newItem.IsDivisibleByFiveText = IsWednesday ? "wuzz" : "buzz";
                    }

                    Results.Add(newItem);
                }

                if (Results.Count > 0)
                {
                    TotalPages = Results.Count / this.PageSize;
                    if (Results.Count % this.PageSize != 0 && Results.Count > this.PageSize)
                        TotalPages += 1;
                    else if (Results.Count > 0 && Results.Count < this.PageSize)
                        TotalPages = 1;
                }
            }
        }
    }
}

Fizzbuzz/Models/FizzbuzzResultItem.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Fizzbuzz.Models
{
    public class FizzbuzzResultItem
    {
        public int Value { get; set; }
        public bool IsDivisibleByThree { get; set; }
        public bool IsDivisibleByFive { get; set; }
        public string IsDivisibleByThreeText { get; set; }
        public string IsDivisibleByFiveText { get; set; }
    }
}

Fizzbuzz/Controllers/FizzbuzzController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Web;
using System.Web.Mvc;
using Fizzbuzz.Models;
using FizzbuzzWebApiService.Models;

namespace Fizzbuzz.Controllers
{
    public class FizzbuzzController : Controller
    {      
        public ActionResult Index()
        {
            FizzbuzzModel model = new FizzbuzzModel();
            if (Session != null && Session["FizzbuzzModel"] != null)
                Session["FizzbuzzModel"] = null;
            ViewBag.UserName = System.Environment.UserName;
            return View(model);
        }

        [HttpPost]
        public ActionResult Results(FizzbuzzModel myFizzbuzzModel, bool generateResults = true)
        {
            if (Request != null &&
                Request.Form != null &&
                Session != null )
            { 
                if (Request.Form["previousButton"] != null)
                {
                    FizzbuzzModel myModel = (FizzbuzzModel)Session["FizzbuzzModel"];
                    if (myModel.CurrentPage > 1)
                        myModel.CurrentPage--;
                    Session["FizzbuzzModel"] = myModel;
                    myFizzbuzzModel = myModel;
                }
                else if (Request.Form["nextButton"] != null)
                {
                    FizzbuzzModel myModel = (FizzbuzzModel)Session["FizzbuzzModel"];
                    if (myModel.CurrentPage < myModel.TotalPages)
                        myModel.CurrentPage++;
                    Session["FizzbuzzModel"] = myModel;
                    myFizzbuzzModel = myModel;
                }
                else if (generateResults)
                {
                    myFizzbuzzModel.GenerateResults();
                    if (Session != null && Session["FizzbuzzModel"] != null)
                        Session["FizzbuzzModel"] = myFizzbuzzModel;

                    using (var client = new HttpClient())
                    {
                        client.BaseAddress = new Uri("http://localhost:25693");
                        
                        client.DefaultRequestHeaders.Accept.Clear();
                        client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                        //var response = client.GetAsync("Api/User/3").Result;
                        var response = client.PostAsJsonAsync("Api/User", new User
                        {
                            UserName = System.Environment.UserName,
                            Value = myFizzbuzzModel.Count
                        }).Result;

                        UserDTO returnValue = response.Content.ReadAsAsync<UserDTO>().Result;


                        //var response = client.PostAsync("Api/User", "www");
                        //if (response..IsSuccessStatusCode)
                        //{
                        //    string responseString = response.Content.ReadAsStringAsync().Result;
                        //}
                    }
                }
            }

            return View(myFizzbuzzModel);
        }
    }
}

Fizzbuzz/Views/Fizzbuzz/Index.cshtml
@model Fizzbuzz.Models.FizzbuzzModel

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Welcome - @ViewBag.UserName</h2>


@using (Html.BeginForm("Results", "Fizzbuzz",FormMethod.Post))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.Label("Enter a whole number", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                
                @Html.EditorFor(model => model.Count, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Count, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Begin" class="btn btn-default" />
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Fizzbuzz/Views/Fizzbuzz/Results.cshtml
@model Fizzbuzz.Models.FizzbuzzModel


@{
    ViewBag.Title = "Results";

}

<link rel="stylesheet" href="~/css/site.css" />
<h2>These are your results</h2>
<hr>
<p>
    Page @Model.CurrentPage Of @Model.TotalPages
</p>
<hr>

@using (Html.BeginForm("Results", "Fizzbuzz", FormMethod.Post))
{
    <div>
        @if (Model.Results != null && Model.Results.Count > 0)
        {
            int counter = 0;
            int startPosition = (Model.CurrentPage * Model.PageSize) - Model.PageSize;
            int endPosition = startPosition + Model.PageSize;
            foreach (Fizzbuzz.Models.FizzbuzzResultItem modelItem in Model.Results)
            {
                if (counter >= startPosition && counter < endPosition)
                {
                    if (modelItem.IsDivisibleByFive && modelItem.IsDivisibleByThree)
                    {
                        <p>
                            <span class="fizz-text">
                                @Html.DisplayFor(model => modelItem.IsDivisibleByThreeText)
                            </span>
                            <span class="buzz-text">
                                @Html.DisplayFor(model => modelItem.IsDivisibleByFiveText)
                            </span>
                        </p>
                    }
                    else if (modelItem.IsDivisibleByFive)
                    {
                        <p>
                            <span class="buzz-text">
                                @Html.DisplayFor(item => @modelItem.IsDivisibleByFiveText)
                            </span>
                        </p>
                    }
                    else if (modelItem.IsDivisibleByThree)
                    {
                        <p>
                            <span class="fizz-text">
                                @Html.DisplayFor(item => @modelItem.IsDivisibleByThreeText)
                            </span>
                        </p>
                    }
                    else
                    {
                        <p>
                            @Html.DisplayFor(item => @modelItem.Value)
                        </p>
                    }
                }

                counter++;
            }
        }
    </div>
    <hr>
    <p>
        Page @Model.CurrentPage Of @Model.TotalPages
    </p>

    if (Model.TotalPages > 1)
    {
        <hr>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                @if (Model.CurrentPage > 1)
                {
                    <input type="submit" name="previousButton" value="Previous" class="btn btn-default" />
                }
                @if (Model.CurrentPage < Model.TotalPages)
                {
                    <input type="submit" name="nextButton" value="Next" class="btn btn-default" />
                }
            </div>
        </div>
    }
}
<hr>

Fizzbuzz/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My Fizzbuzz Test</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Fizzbuzz Test", "Index", "Fizzbuzz", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My Fizzbuzz Test</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>